version: '3.9'

services:
  huiszoeker:
    build: .
    container_name: huiszoeker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data       # bestaande data
      - ./app:/app             # bind mount je code, zodat wijzigingen direct zichtbaar zijn
    shm_size: 512m
    command: python pararus.py  # start je script automatisch

  webinterface:
    build: .
    container_name: huiszoeker-web
    restart: unless-stopped
    ports:
      - '5000:5000'
    volumes:
      - ./data:/app/data       # bestaande data
      - ./app:/app             # bind mount je code, zodat wijzigingen in web.py direct zichtbaar zijn
    command: python web.py